# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d77d3b2e6a9cdef7f9c98a239da45505f9dff7f59a8cb652d66ad73f40861b712ae7c4ec3378448011581cff1f887ca772a8ff4dec2bdffa97838c4e85076b3f

test:
  secret_key_base: a3cd41817341fadbae2a3a6928b74acea5f83e9af3bff339a1ff4a4f5bce623f2ac9a3db50582cda4783b1146bc15ecc278d39b1fbe421234f1a8ceb75f1feea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
